Lint/UnusedMethodArgument:
  Enabled: true
  AutoCorrect: false

Lint/UnusedBlockArgument:
  Enabled: true
  AutoCorrect: false

Naming/VariableNumber:
  CheckSymbols: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/LineLength:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
